module.exports = {
  allowedStartRules: [
    'Rules',
    'Rule',
    'Condition',
    'Effects',
    'Question',
    'Item',
    'VariableName',
    'QuestionString',
    'ItemNameAndWeight',
    'CategoryName',
  ],
  dts: true,
  format: 'es',
  input: 'src/schemas/rules.peggy',
  output: 'src/index.mjs',
  returnTypes: {
    CategoryName: 'string',
    Condition: 'Condition',
    Effects: '(Item | Question)[]',
    Item: 'Item',
    ItemNameAndWeight: '{ weight: number | undefined, name: string }',
    Question: 'Question',
    QuestionString: 'string',
    Rule: 'Rule',
    Rules: 'Rules',
    VariableName: 'string',
  },
  trace: false,
};
